version: '3.8'

services:
  codebuddy2api:
    # 使用当前目录下的 Dockerfile 进行构建
    build: .
    # 为构建的镜像命名
    image: xueyue052/codebuddy2api:latest
    # 容器的重启策略
    restart: unless-stopped
    # 将容器的 8001 端口映射到宿主机的 8001 端口
    ports:
      - "8001:8001"
    # 数据卷挂载，用于持久化配置和凭证
    volumes:
      # 将本地的 config.json 文件挂载到容器内，实现配置持久化
      # 注意：在首次运行前，请确保本地存在一个空的 config.json 文件
      # 注意：现在挂载的是整个config目录
      - ./config:/app/config
      # 将本地的凭证目录挂载到容器内，实现凭证持久化
      - ./.codebuddy_creds:/app/.codebuddy_creds
    # 加载 .env 文件中的环境变量
    env_file:
      - .env